### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by weirdlobster** [ryneches/SuchTree#15]
Hi there, I really want to use this for combining phylo's and heatmaps but my jupyter notebook is installed through conda because it usually makes things easy to install. Pip won't install to my conda python--are you going to submit this to conda?

**Comment by ryneches** [comment]
Hey @weirdlobster! Sorry for the late reply. Yes, I would like to submit this to conda! I started working on it around the time the JOSS paper came out, but I ran out of brain space to figure out conda's packaging system. If you're familiar with it, I wouldn't mind some help...
