### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Mass23** [ryneches/SuchTree#16]
Dear SuchTree team,

I tried to open a tree that has around 561'000 leaves using SuchTree in a jupyter notebook using the loading function: `tree = SuchTree('Data/tree.newick')`. However, I am getting a maximum recursion depth exceeded error:

`---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-3-939f5fc5a80e> in <module>
      4 sys.setrecursionlimit(10000)
      5 
----> 6 PP1_tree = SuchTree('Data/PP1_tree.newick')
      7 print( 'nodes : %d, leafs : %d' % ( PP1_tree.length, len(PP1_tree.leafs) ) )

SuchTree/SuchTree.pyx in SuchTree.SuchTree.SuchTree.__init__()

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/datamodel/treemodel.py in get(cls, **kwargs)
   2756 
   2757         """
-> 2758         return cls._get_from(**kwargs)
   2759 
   2760     def yield_from_files(cls,

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/datamodel/basemodel.py in _get_from(cls, **kwargs)
    152             raise e
    153         if src_type == "file" or src_type == "stream":
--> 154             return cls.get_from_stream(src=src, schema=schema, **kwargs)
    155         elif src_type == "path":
    156             return cls.get_from_path(src=src, schema=schema, **kwargs)

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/datamodel/basemodel.py in get_from_stream(cls, src, schema, **kwargs)
    188         return cls._parse_and_create_from_stream(stream=src,
    189                 schema=schema,
--> 190                 **kwargs)
    191     get_from_stream = classmethod(get_from_stream)
    192 

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/datamodel/treemodel.py in _parse_and_create_from_stream(cls, stream, schema, collection_offset, tree_offset, **kwargs)
   2661                     taxon_namespace_factory=tns_factory,
   2662                     tree_list_factory=tree_list_factory,
-> 2663                     global_annotations_target=None)
   2664         if not tree_lists:
   2665             raise ValueError("No trees in data source")

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/dataio/ioservice.py in read_tree_lists(self, stream, taxon_namespace_factory, tree_list_factory, global_annotations_target)
    373                 char_matrix_factory=None,
    374                 state_alphabet_factory=None,
--> 375                 global_annotations_target=global_annotations_target)
    376         # if is_post_process_global_annotations:
    377         #     for tree_list in product.tree_lists:

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/dataio/newickreader.py in _read(self, stream, taxon_namespace_factory, tree_list_factory, char_matrix_factory, state_alphabet_factory, global_annotations_target)
    324         for tree in self.tree_iter(stream=stream,
    325                 taxon_symbol_mapper=taxon_symbol_mapper,
--> 326                 tree_factory=tree_factory):
    327             pass
    328         product = self.Product(

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/dataio/newickreader.py in tree_iter(self, stream, taxon_symbol_mapper, tree_factory)
    302                     nexus_tokenizer=nexus_tokenizer,
    303                     tree_factory=tree_factory,
--> 304                     taxon_symbol_map_fn=taxon_symbol_mapper.require_taxon_for_symbol)
    305             yield tree
    306             if tree is None:

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/dataio/newickreader.py in _parse_tree_statement(self, nexus_tokenizer, tree_factory, taxon_symbol_map_fn)
    384                 current_node=tree.seed_node,
    385                 taxon_symbol_map_fn=taxon_symbol_map_fn,
--> 386                 is_internal_node=None)
    387         current_token = nexus_tokenizer.current_token
    388         if not self._tree_statement_complete:

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/dataio/newickreader.py in _parse_tree_node_description(self, nexus_tokenizer, tree, current_node, taxon_symbol_map_fn, is_internal_node)
    560                             current_node=new_node,
    561                             taxon_symbol_map_fn=taxon_symbol_map_fn,
--> 562                             is_internal_node=is_new_internal_node,
    563                             )
    564                     current_node.add_child(new_node);

... last 1 frames repeated, from the frame below ...

~/opt/anaconda3/lib/python3.7/site-packages/dendropy/dataio/newickreader.py in _parse_tree_node_description(self, nexus_tokenizer, tree, current_node, taxon_symbol_map_fn, is_internal_node)
    560                             current_node=new_node,
    561                             taxon_symbol_map_fn=taxon_symbol_map_fn,
--> 562                             is_internal_node=is_new_internal_node,
    563                             )
    564                     current_node.add_child(new_node);

RecursionError: maximum recursion depth exceeded while calling a Python object`

I tried to set manually a higher recursion limit using `sys.setrecursionlimit()`, but when I increase it I get a dead kernel, and the maximal value that does not kill the kernel is not sufficient to load the tree.

Kernel information: `Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.`

I am using a MacBook Pro 15'' - 2017, 16gb RAM, quad-core i7 running on macos Big Sur 11.1.

Thanks a lot!

Best regards,

Mass23

**Comment by ryneches** [comment]
Yikes, that must be either an exceedingly deep tree, or it may not be strictly branching. I don't support non-tree-like-trees yet, but that's in the works.

How was this tree constructed?
