### ISSUE TITLE
Polytomies?

### ISSUE THREAD

**Issue by mmore500** [ryneches/SuchTree#24]
Does SuchTree support representation of polytomies? I see they're being resolved away in the `SuchTree` constructor, just curious whether this is a fundamental limitation.

<https://github.com/ryneches/SuchTree/blob/1c7207b1980806bcf33eb45f6b3f0b8c6267ca94/SuchTree/MuchTree.pyx#L124>

**Comment by ryneches** [comment]
The base node structure is always binary, and there is a small finite branch length to represent polytomies. So, you can load a tree with polytomies, and the distance calculations will work out correctly to within a user-defined precision. But, it will not be logically represented as a polytomy.

Whether that is a limitation or not depends on your application. SuchTree is really intended for numerical sampling of distances. In that application it is not really a limitation.
